[package]
name = "function-calling"
version = "0.1.0"
edition = "2021"

[dependencies]
instructor-ai = "0.1.0"
instruct-macros = "0.1.1"
openai-api-rs = "4.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
instruct-macros-types = "0.1.2"
